//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuncionarioApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Xml", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Xml : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FuncionarioApp.ServiceReference1.Funcionario[] funcionariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public FuncionarioApp.ServiceReference1.Funcionario[] funcionarios {
            get {
                return this.funcionariosField;
            }
            set {
                if ((object.ReferenceEquals(this.funcionariosField, value) != true)) {
                    this.funcionariosField = value;
                    this.RaisePropertyChanged("funcionarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Funcionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idt_funcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_residencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_nascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string idt_func {
            get {
                return this.idt_funcField;
            }
            set {
                if ((object.ReferenceEquals(this.idt_funcField, value) != true)) {
                    this.idt_funcField = value;
                    this.RaisePropertyChanged("idt_func");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfField, value) != true)) {
                    this.cpfField = value;
                    this.RaisePropertyChanged("cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rg {
            get {
                return this.rgField;
            }
            set {
                if ((object.ReferenceEquals(this.rgField, value) != true)) {
                    this.rgField = value;
                    this.RaisePropertyChanged("rg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string tel_residencial {
            get {
                return this.tel_residencialField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_residencialField, value) != true)) {
                    this.tel_residencialField = value;
                    this.RaisePropertyChanged("tel_residencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tel_celular {
            get {
                return this.tel_celularField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_celularField, value) != true)) {
                    this.tel_celularField = value;
                    this.RaisePropertyChanged("tel_celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string data_nascimento {
            get {
                return this.data_nascimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.data_nascimentoField, value) != true)) {
                    this.data_nascimentoField = value;
                    this.RaisePropertyChanged("data_nascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FuncionariosSoap")]
    public interface FuncionariosSoap {
        
        // CODEGEN: Generating message contract since element name sexo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterFuncionariosPorSexo", ReplyAction="*")]
        FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoResponse ObterFuncionariosPorSexo(FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterFuncionariosPorSexo", ReplyAction="*")]
        System.Threading.Tasks.Task<FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoResponse> ObterFuncionariosPorSexoAsync(FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterFuncionariosPorSexoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterFuncionariosPorSexo", Namespace="http://tempuri.org/", Order=0)]
        public FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequestBody Body;
        
        public ObterFuncionariosPorSexoRequest() {
        }
        
        public ObterFuncionariosPorSexoRequest(FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterFuncionariosPorSexoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sexo;
        
        public ObterFuncionariosPorSexoRequestBody() {
        }
        
        public ObterFuncionariosPorSexoRequestBody(string sexo) {
            this.sexo = sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterFuncionariosPorSexoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterFuncionariosPorSexoResponse", Namespace="http://tempuri.org/", Order=0)]
        public FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoResponseBody Body;
        
        public ObterFuncionariosPorSexoResponse() {
        }
        
        public ObterFuncionariosPorSexoResponse(FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterFuncionariosPorSexoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public FuncionarioApp.ServiceReference1.Xml Xml;
        
        public ObterFuncionariosPorSexoResponseBody() {
        }
        
        public ObterFuncionariosPorSexoResponseBody(FuncionarioApp.ServiceReference1.Xml Xml) {
            this.Xml = Xml;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FuncionariosSoapChannel : FuncionarioApp.ServiceReference1.FuncionariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FuncionariosSoapClient : System.ServiceModel.ClientBase<FuncionarioApp.ServiceReference1.FuncionariosSoap>, FuncionarioApp.ServiceReference1.FuncionariosSoap {
        
        public FuncionariosSoapClient() {
        }
        
        public FuncionariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FuncionariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoResponse FuncionarioApp.ServiceReference1.FuncionariosSoap.ObterFuncionariosPorSexo(FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequest request) {
            return base.Channel.ObterFuncionariosPorSexo(request);
        }
        
        public FuncionarioApp.ServiceReference1.Xml ObterFuncionariosPorSexo(string sexo) {
            FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequest inValue = new FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequest();
            inValue.Body = new FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequestBody();
            inValue.Body.sexo = sexo;
            FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoResponse retVal = ((FuncionarioApp.ServiceReference1.FuncionariosSoap)(this)).ObterFuncionariosPorSexo(inValue);
            return retVal.Body.Xml;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoResponse> FuncionarioApp.ServiceReference1.FuncionariosSoap.ObterFuncionariosPorSexoAsync(FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequest request) {
            return base.Channel.ObterFuncionariosPorSexoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoResponse> ObterFuncionariosPorSexoAsync(string sexo) {
            FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequest inValue = new FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequest();
            inValue.Body = new FuncionarioApp.ServiceReference1.ObterFuncionariosPorSexoRequestBody();
            inValue.Body.sexo = sexo;
            return ((FuncionarioApp.ServiceReference1.FuncionariosSoap)(this)).ObterFuncionariosPorSexoAsync(inValue);
        }
    }
}
